TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#=============================
# Build the IOC application

PROD_IOC = ics-dg-com
# ics-dg-com.dbd will be created and installed
DBD += ics-dg-com.dbd

# ics-dg-com.dbd will be made up from these files:
ics-dg-com_DBD += base.dbd

# Include dbd files from all support applications:
#ics-dg-com_DBD += xxx.dbd

# Add all the support libraries needed by this IOC
#ics-dg-com_LIBS += xxx

# ics-dg-com_registerRecordDeviceDriver.cpp derives from ics-dg-com.dbd
ics-dg-com_SRCS += ics-dg-com_registerRecordDeviceDriver.cpp

# Build the main IOC entry point on workstation OSs.
ics-dg-com_SRCS_DEFAULT += ics-dg-comMain.cpp
ics-dg-com_SRCS_vxWorks += -nil-

# Add support from base/src/vxWorks if needed
#ics-dg-com_OBJS_vxWorks += $(EPICS_BASE_BIN)/vxComLibrary

# Finally link to the EPICS Base libraries
ics-dg-com_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

